# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgUoSDFOlPoq9CsKBvmz7BIpdSzfBRCq
"""

import pandas as p
import numpy as n
import matplotlib.pyplot as plt

#Classification of x,y using iloc
df=p.read_csv("/content/Social_Network_Ads.csv")
x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values
x

#importing training and testing models
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
y_test

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_test

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

print("Total no. of incorrect predictions are:",cm[0][1]+cm[1][0])

