# -*- coding: utf-8 -*-
"""PLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKTMof1Fs8UCxbyrdRCd973QG8tOF0iw
"""

import numpy as n
import matplotlib.pyplot as plt
import pandas as p

#Read csv file and seperate dependent and independent values
df= p.read_csv("/content/Position_Salaries.csv")
x=df.iloc[:,1:2].values
y=df.iloc[:,2].values
x,y

#Use linear regression
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)

#Building a polynomial model
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x)
lin_reg2=LinearRegression()
lin_reg2.fit(x_poly,y)

#Scatter plot of linear regression model
plt.scatter(x,y,color='red')
plt.plot(x,regressor.predict(x),color='blue')
plt.title('Linear regression of Position to salary')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.legend()
plt.show()

#Visualising polynomial regression
plt.scatter(x,y,color='red')
plt.plot(x,lin_reg2.predict(poly_reg.fit_transform(x)),color='blue')
plt.title('Polynomial regression of Position to salary')
plt.xlabel('Position leval')
plt.ylabel('Salary')
plt.legend()
plt.show()

"""**bold text**"""

regressor.predict([[6]])#linear reg prediction at level=6

lin_reg2.predict(poly_reg.fit_transform([[6]]))#Poly reg prediction at level=6

"""The actual value in data set is 150000 whereas polynomial regression predicted 1.43 lakh

"""





