# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZFBPQ_xhHJQ4Obq-b45lCSdG8pFg46-
"""

import numpy as n
import pandas as p
df=p.read_csv("/content/Social_Network_Ads.csv")

x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values

#split the data set into train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
y_train

#featurescaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

#fitting SVM to the model
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

y_pred

#Making confusion  matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

print("No. of false predictions are ",cm[0][1]+cm[1][0])

